---
- name: Publicar página principal da aplicação
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ app_document_root }}/index.html"
    owner: nginx
    group: nginx
    mode: "0644"
  become: true
  notify: Reload nginx

- name: Registrar release atual
  ansible.builtin.copy:
    dest: "{{ app_document_root }}/RELEASE"
    content: "{{ app_release_label }}\n"
    owner: nginx
    group: nginx
    mode: "0644"
  become: true

- name: Criar página de saúde da aplicação
  ansible.builtin.copy:
    dest: "{{ app_document_root }}{{ app_healthcheck_path }}"
    content: "OK"
    owner: nginx
    group: nginx
    mode: "0644"
  become: true
