---
- name: Garantir diretório de releases da aplicação
  ansible.builtin.file:
    path: /opt/app/releases
    state: directory
    owner: apache
    group: apache
    mode: "0755"
  become: true

- name: Fazer checkout da versão solicitada
  ansible.builtin.git:
    repo: "{{ app_repository_url }}"
    version: "{{ app_version }}"
    dest: "/opt/app/releases/{{ app_version }}"
    update: true
    force: true
  become: true
  register: app_checkout

- name: Atualizar conteúdo publicado
  ansible.builtin.copy:
    src: "/opt/app/releases/{{ app_version }}/"
    dest: "{{ app_document_root }}/"
    owner: apache
    group: apache
    remote_src: true
  become: true
  notify: Reiniciar httpd

- name: Registrar release ativo
  ansible.builtin.copy:
    dest: "/opt/app/CURRENT"
    content: "{{ app_version }}\n"
    owner: apache
    group: apache
    mode: "0644"
  become: true

- name: Criar página de saúde da aplicação
  ansible.builtin.copy:
    dest: "{{ app_document_root }}/healthz.html"
    content: "OK"
    owner: apache
    group: apache
    mode: "0644"
  become: true
