---
- name: Atualizar aplicação Nginx com nova release
  hosts: tag_Role_web
  become: true
  serial: 1
  vars_files:
    - ../group_vars/all.yml
  vars:
    desired_release: "{{ new_release | default(app_release_label) }}"
  pre_tasks:
    - name: Validar release informada
      ansible.builtin.assert:
        that:
          - desired_release is defined
          - desired_release | string | length > 0
        fail_msg: "Informe a variável new_release=<identificador> ao executar o playbook."
  roles:
    - role: app
      vars:
        app_release_label: "{{ desired_release }}"
